#The below properties can be overridden with environment variables by passing JVM parameters e.g. -Dspring.datasource.username=bob
#Refer the link: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-application-property-files
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: paymentuser
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://localhost:5432/paymentdb
    user: paymentuser
    password: password
    enabled: true
    locations: classpath:/db/migration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    show-details: always

resilience4j.circuitbreaker:
  instances:
    bankservice:
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException

resilience4j.retry:
  instances:
    bankservice:
      maxRetryAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException


Server:
  port: 8080
