spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

resilience4j.circuitbreaker:
  instances:
    bankservice:
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException

resilience4j.retry:
  instances:
    bankservice:
      maxRetryAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 1
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException

